### ISSUE TITLE
can.List.each iterates uninitialised values

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-list#12]
From: https://github.com/canjs/canjs/issues/2163

can.List::each is documented as not iterating through `undefined` values, but it does.

We should mimic whatever Array.prototype.forEach does.

**Comment by prashantsharmain** [comment]
@kylegifford Sorry, but I just saw you tagged this "in progress". Did you intend to take this up? If yes, I'll assign this to you.

**Comment by prashantsharmain** [comment]
@justinbmeyer Does this need to be done for both can.List.prototype.each and can.List.prototype.forEach?  can.List.prototype.each borrows the behavior from can.Map.prototype.each

**Comment by justinbmeyer** [comment]
@kylegifford is our automated system.  We might need to change that to "Waffle.io".  Yes, it should be the same for everything.

**Comment by kylegifford** [comment]
@justinbmeyer I created https://github.com/bitovi/extracurriculars/issues/75 to track this.

**Comment by prashantsharmain** [comment]
@justinbmeyer @akagomez I just submitted a fix through PR #15. Could either of you take a quick look and let me know if it's good to be merged in?
