### ISSUE TITLE
"Unable to bind change" when having CanList items with function properties

### ISSUE THREAD

**Issue by ivospinheiro** [canjs/can-list#97]
The following error is thrown when binding to a CanList item with properties as functions.
![image](https://user-images.githubusercontent.com/4503714/63531724-0b7ea880-c501-11e9-9a07-1a7e14a2ec14.png)

Here is a sample project that shows the error:
https://jsbin.com/genelodasu/edit?html,console,output

**Comment by cherifGsoul** [comment]
The fix of this issue is at https://github.com/canjs/can-map/pull/146
